### ISSUE TITLE
Update to Babel 6

### ISSUE THREAD

**Issue by luandro** [luandro/hapi-universal-redux#77]
React-Transform not yet compatible, issue being tracked [here](https://github.com/gaearon/babel-plugin-react-transform/issues/46).

**Comment by luandro** [comment]
Tracking [this](https://github.com/gaearon/babel-plugin-react-transform/pull/50) instead.

**Comment by luandro** [comment]
Error with client babel transpiling:

```
Module build failed: ReferenceError: [BABEL] .../hapi-universal-redux/src/client.js: Unknown option: base.stage
```

**Comment by dbashford** [comment]
That is because of this: https://github.com/luandro/hapi-universal-redux/blob/master/babel-server.js#L2

Now you set up your `stage` by using presets, canonically in a `.babelrc` file.

``` javascript
{
  "presets": ["stage-0"]
}
```

There are probably better ways to do it, but I just have this in the stuff I am doing:

``` javascript
require("babel-core/register")({});
```

I haven't bothered to see if the object is necessary. ;)

**Comment by luandro** [comment]
Thanks for the heads up, I've been really busy lately. As soon as I have some time I'll do a big update to keep up with the [original fork](https://github.com/RickWong/react-isomorphic-starterkit), which is already using Babel 6 and has figured a way to stop using [Piping](https://www.npmjs.com/package/piping) for server reload, which makes things really slow.
